# Automatically build all three projects for every push and pull request.
name: build
on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: validate class tweaker
        run: ./gradlew :fabric:validateAccessWidener --warning-mode all
      - name: build
        run: ./gradlew build --warning-mode all
      - name: capture project artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            common/build/libs/
            fabric/build/libs/
            neoforge/build/libs/
